1-Write a NumPy program to test whether none of the elements of a given array is zero.

In [2]:
import numpy as np
arr1=np.array([1, 2, 3, 4, 0, 9, 7])
if np.all(arr1!=0):
    print('None of the emelents is Zero')
else: print('One or more of the emelents is Zero')
        


One or more of the emelents is Zero


2-Write a NumPy program to test whether any of the elements of a given array is non-zero

In [30]:
arr1=np.array([0, 0, 0, 4, 0, 0, 0])
if np.all(arr1==0):
    print('None of the emelents is non-Zero')
else: print('All elements are Zeros')

None of the emelents is non-Zero


3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays

In [44]:
arr1=np.array([1, 2, 3, 4, 0, 9, 7])
arr2=np.array([1, 2, 3, 4, 0, 9, 7])
if np.all(arr1==arr2) or np.allclose(arr1,arr2):
    print('Comparison - equal within a tolerance')
else: print('Comparison - Not equal within a tolerance:')

Comparison - equal within a tolerance


4.Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [55]:
arr1=np.concatenate((np.zeros(10),np.ones(10),np.ones(10)*5),axis=None)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


5. Write a NumPy program to create an array of the integers from 30 to70.

In [16]:
arr1=np.arange(30,70)
print(arr1)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


6. Write a NumPy program to create a 3x3 identity matrix

In [60]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7. Write a NumPy program to generate a random number between 0 and 1

In [12]:
print(np.random.normal(0,1,1))

[0.32050236]


 8.Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [15]:
print(np.random.normal(0,1,15))

[-1.33821364 -0.76542453  1.01990722  1.14545516 -0.27029609  0.39045017
  0.45746433 -0.01101924 -1.30880911  1.14728812  0.39057095 -1.44161105
  0.31957305  1.39815808  0.73468381]


9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [18]:
arr1=np.arange(15,55)
print(arr1[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [ ]:
x = np.random.randint(0, 11, 5)

11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [35]:
arr1=np.zeros((10,10),dtype='int16')
arr1[0]=1
arr1[9]=1
arr1[:,0]=1
arr1[:,9]=1
print(arr1)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [54]:
arr1=np.identity((5),dtype='int16')
arr1[arr1>0]=[1,2,3,4,5]
print(arr1)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [86]:
arr1=np.zeros((4,4),dtype='int16')
arr1[0::2,1::2]=1
arr1[1::2,0::2]=1
print(arr1)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

In [91]:
import os
x = np.arange(10)
y = np.arange(11, 20)
print("Original arrays:")
print(x)
print(y)

# Saving the arrays 'x' and 'y' into a '.npz' file named 'temp_arra.npz' using np.savez()
np.savez('temp_arra.npz', x=x, y=y)

# Printing a message indicating loading arrays from the 'temp_arra.npz' file
print("Load arrays from the 'temp_arra.npz' file:")

# Loading data from 'temp_arra.npz' into variables 'x2' and 'y2' using np.load()
with np.load('temp_arra.npz') as data:
    x2 = data['x']
    y2 = data['y']
    
    # Printing the loaded arrays 'x2' and 'y2'
    print(x2)
    print(y2) 

Original arrays:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
Load arrays from the 'temp_arra.npz' file:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select

In [90]:
np.random.seed(10)

# Generating an array of 40 random numbers from a uniform distribution [0, 1)
print(np.random.rand(40)) 

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895
 0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006
 0.11398436 0.82868133 0.04689632 0.62628715]


16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [89]:
arr1=np.array([1, 2, 3, 4, 0, 9, 7])
print(arr1[arr1>3])
print(arr1[arr1<3])

[4 9 7]
[1 2 0]
